# Generated by Django 5.1.6 on 2025-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='social/prof/dc1.png', upload_to='social/prof/'),
        ),
    ]
