# Generated by Django 5.1.6 on 2025-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='club',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profileimg',
            field=models.ImageField(default='social/prof/dc1.png', upload_to='profile_pics/'),
        ),
    ]
